# ==========================
# API REST (Rust) + Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest-rust
  template:
    metadata:
      labels:
        app: api-rest-rust
    spec:
      containers:
        - name: api-rest-rust
          image: 34.59.249.209:5000/proyecto/api-rest-rust:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_SERVER_ADDR
              value: "http://grpc-server-svc:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest-svc
spec:
  selector:
    app: api-rest-rust
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

# ==========================
# gRPC Server (Go) + Service
# ==========================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server-go
  template:
    metadata:
      labels:
        app: grpc-server-go
    spec:
      containers:
        - name: grpc-server-go
          image: 34.59.249.209:5000/proyecto/grpc-server-go:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-svc
spec:
  selector:
    app: grpc-server-go
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP

# ==========================
# gRPC Client (Go) + Service
# (normalmente el "client" no se expone,
#  pero lo dejamos con service por pruebas)
# ==========================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-go
  template:
    metadata:
      labels:
        app: grpc-client-go
    spec:
      containers:
        - name: grpc-client-go
          image: 34.59.249.209:5000/proyecto/grpc-client-go:1.0
          imagePullPolicy: Always
          env:
            # Ajusta estas variables al nombre que tu app use
            - name: GRPC_SERVER_ADDR
              value: "grpc-server-svc:50051"
            - name: API_REST_URL
              value: "http://api-rest-svc:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-svc
spec:
  selector:
    app: grpc-client-go
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
